### ISSUE TITLE
Handle UTF-8 BOM

### ISSUE THREAD

**Issue by JamieMagee** [rcjsuen/dockerfile-ast#106]
When a Dockerfile begins with a UTF-8 BOM, the first instruction is not parsed correctly. This causes `FROM` statements to be parsed as generic `Instruction`s instead of `From`

I think Visual Studio adds UTF-8 BOMs by default.

**Comment by rcjsuen** [comment]
@JamieMagee Thank you for your bug report and apologies for not responding to this earlier. I have a fix but will need to confirm the behaviour of how offsets are handled in the language server protocol if a BOM is found.

**Comment by rcjsuen** [comment]
@JamieMagee I have just released 0.5.0 which includes a fix for this. Please let me know if it resolves your issue.

**Comment by JamieMagee** [comment]
Yep, this solves my issue. Thank you!
