### ISSUE TITLE
Comments at the beginning of the file

### ISSUE THREAD

**Issue by tdurieux** [rcjsuen/dockerfile-ast#110]
Is there a reason why comments at the beginning of the file are not considered in the AST.
I expect it is related to https://github.com/rcjsuen/dockerfile-ast/blob/a93815f37ca05aa3ec62b47647f8f0451432519e/src/parser.ts#L190-L191 
But I don't understand the reason for this. Could I have an explanation?

**Comment by rcjsuen** [comment]
> Is there a reason why comments at the beginning of the file are not considered in the AST.

It depends on whether it's a parser directive or not. In the general case it should be considered a comment. Could you provide an example where it's not in the list of comments? If you have parser directives you can use the `getDirectives()` function to get them.
```TypeScript
import { DockerfileParser } from "dockerfile-ast";
let dockerfile = DockerfileParser.parse("#Comment\nFROM alpine");
let comments = dockerfile.getComments();
console.log(comments);
```
```
[
  Comment {
    document: FullTextDocument {
      _uri: '',
      _languageId: '',
      _version: 0,
      _content: '#Comment\nFROM alpine',
      _lineOffsets: [Array]
    },
    range: { start: [Object], end: [Object] }
  }
]
```

**Comment by tdurieux** [comment]
I don't remember the case :/ We can close for now and I would reopen if I found a test case.
