### ISSUE TITLE
Simplest way to resolve an ARG or ENV in FROM

### ISSUE THREAD

**Issue by robcresswell** [rcjsuen/dockerfile-ast#47]
More of a question than an issue I suppose, but what's the most straightforward way to resolve the variable substitution in these situations? I browsed the code and tests for some time, but most of the usages in the test cases seem to rely on already knowing the name of the variable you're looking to substitute, for example:

```js
dockerfile.resolveVariable("ver", 1);
```

I was wondering if there is something more along the lines of

```js
const parsedContents = DockerfileParser.parse(contents);
const from = parsedContents.getFROMs().pop() as From;

from.getResolvedImage();
```

It seems the current approach would be to write the regex matcher myself to pull `${}` from the image name, and then run the resolver? This is fine with me, but just wanted to check if I was missing a trick.

**Comment by robcresswell** [comment]
Cool, thanks for the quick response! The library is generally a joy to work with, the code / tests are very self-explanatory. Happy for me to close the issue?

**Comment by rcjsuen** [comment]
Thank you for your kind words, @robcresswell. I hope the library continues to be helpful to you!
