### ISSUE TITLE
Docker image name incorrectly identified as registry in FROM

### ISSUE THREAD

**Issue by daimor** [rcjsuen/dockerfile-ast#59]
Docker hub has images from verified publishers, and such image names starts with `store/`
For example
`store/intersystems/iris-community` [link](https://hub.docker.com/_/intersystems-iris-data-platform)
`store/intersystems/irishealth` [link](https://hub.docker.com/_/intersystems-iris-for-health)
`store/splunk/universalforwarder` [link](https://hub.docker.com/_/splunk-universal-forwarder)
on so on

At the moment parser recognizes `store` as registry but in this case it is just a part of image name

To be solved for https://github.com/microsoft/vscode-docker/issues/1337

**Comment by rcjsuen** [comment]
@daimor This opens up an interesting can of worms as you could have any arbitrary word in front of the image's name and have that be a Docker registry given your local DNS settings or whatever. I wonder how Docker implements this on their end. Could they be hardcoding the word `store` in their handling of `Dockerfile`s?

**Comment by daimor** [comment]
Well, I found [this code](https://github.com/docker/distribution/blob/ae2e973db9365d6f8401ffb6bfc603f3cd76b111/reference/normalize.go#L93), which used by docker-cli
```go
// splitDockerDomain splits a repository name to domain and remotename string.
// If no valid domain is found, the default domain is used. Repository name
// needs to be already validated before.
func splitDockerDomain(name string) (domain, remainder string) {
	i := strings.IndexRune(name, '/')
	if i == -1 || (!strings.ContainsAny(name[:i], ".:") && name[:i] != "localhost") {
		domain, remainder = defaultDomain, name
	} else {
		domain, remainder = name[:i], name[i+1:]
	}
	if domain == legacyDefaultDomain {
		domain = defaultDomain
	}
	if domain == defaultDomain && !strings.ContainsRune(remainder, '/') {
		remainder = officialRepoName + "/" + remainder
	}
	return
}
```
So, it actually means, that `localhost` is hardcoded, and any domain name should contain dots `.` or colon `:`
if no localhost and does not contains `.`, `:` it is just image name.

**Comment by rcjsuen** [comment]
@daimor Well then. You learn something new every day as I always like to say...

Thanks for digging this up!

**Comment by rcjsuen** [comment]
```TypeScript
import { DockerfileParser, From } from './main';
const dockerfile = DockerfileParser.parse("FROM store/base/image");
const from = (dockerfile.getInstructions()[0]) as From;
console.log(from.getImageName());
```
```
base/image
```
We should get `store/base/image` instead.

**Comment by rcjsuen** [comment]
@daimor Thanks for the bug report. Have a great weekend!
